export const strings = {
  en: {
    assets: "My assets",
    assetsHelp:
      "All holdings, their cost and current indicative value. Manage individual records in Purchases.",
    appearance: "Appearance",
    appearanceHelp:
      "Nine themes for your portfolio. Your selection stays on this device.",
    quoteHint: "Current quote · USD",
    manualQuote: "No fresh quote. Enter the actual purchase price manually.",
    historicalPrice:
      "This is today’s indicative quote, not a historical purchase price. Changing the date keeps your entered price.",
    useQuote: "Use current quote",
    overview: "Overview",
    purchases: "Purchases",
    markets: "Market",
    settings: "Your data",
    portfolio: "My portfolio",
    subtitle: "A clear view of what you hold.",
    add: "Add purchase",
    edit: "Edit purchase",
    save: "Save purchase",
    cancel: "Cancel",
    remove: "Delete",
    confirmDelete:
      "Delete this purchase? This updates your holdings and cost basis.",
    saved: "Purchase saved on this device.",
    deleted: "Purchase deleted.",
    undo: "Undo",
    value: "Portfolio value",
    cost: "Total invested",
    pnl: "Unrealized P&L",
    roi: "Return on cost",
    feesIncluded: "Including purchase fees",
    unrealized: "Current value minus cost",
    noCost: "No cost basis",
    holdings: "Your holdings",
    coin: "Coin",
    quantity: "Quantity",
    average: "Avg. buy price",
    price: "Current price",
    purchasePrice: "Price per coin · USD",
    total: "Value",
    allocation: "Allocation",
    history: "Portfolio history",
    observed: "Observed value",
    costLine: "Cost basis",
    historyHelp:
      "Daily snapshots collected while you use Folio. Deposits and edits change the value too; this is not a return chart.",
    historyEmpty: "Your history starts here",
    historyEmptyHelp:
      "After your first purchase, Folio saves a daily valuation when you visit with fresh prices. Come back another day to see the trend.",
    empty: "Make your portfolio yours.",
    emptyHelp:
      "Record your first crypto purchase to see its value, cost and return. No wallet connection needed.",
    local: "Saved on this device",
    localHelp:
      "Your portfolio stays in this browser. Export a backup to keep a copy or move to another device.",
    refresh: "Refresh prices",
    refreshing: "Updating prices…",
    fetched: "Retrieved",
    source: "Source",
    stale:
      "Cached prices — last refresh failed or prices are over 5 minutes old.",
    offline:
      "Prices unavailable. Check your connection and refresh. Your purchases are safe.",
    unknown: "Awaiting prices",
    fee: "Fee · USD",
    date: "Purchase date",
    note: "Note (optional)",
    notePlaceholder: "e.g. Monthly purchase",
    purchaseTotal: "Total cost",
    invalidPurchase:
      "Check the coin, positive quantity, non-negative price and fee, and a valid date no later than today.",
    close: "Close",
    search: "Search coins",
    noResults: "No matching coins.",
    ledgerHelp:
      "Your purchase records. Edit a record to correct its quantity, date or cost.",
    actions: "Actions",
    backup: "Keep a copy of your portfolio",
    export: "Export backup",
    import: "Import backup",
    importHelp:
      "Import a Folio JSON backup. You will review it before replacing your data.",
    exportCsv: "Export purchases · CSV",
    importReview: "Replace this portfolio?",
    importConfirm: "Replace with backup",
    importWarning:
      "This replaces all purchases and history on this device. Export your current portfolio first if you want to keep it.",
    imported: "Backup imported.",
    invalidBackup:
      "This file is not a valid Folio backup. Existing data has not changed.",
    storageError:
      "Browser storage is unavailable or full. Changes cannot be saved. Export your data before closing this page.",
    corrupt:
      "Saved data could not be read. Download it for recovery or import a valid backup. Nothing has been overwritten.",
    recovery: "Download recovery file",
    privacy: "Private by design",
    privacyHelp:
      "No sign-up, tracking cookies or wallet keys. Only public prices are requested from Coinbase, with Kraken as a fallback. Holdings are never sent to either provider.",
    method: "How calculations work",
    methodHelp:
      "Cost = quantity × purchase price + fee. P&L = current value − cost. ROI = P&L ÷ cost. Multiple purchases are grouped by coin using a weighted average. All amounts are in USD. Sales, tax reporting and exchange execution are not supported.",
    marketHelp:
      "Indicative USD quotes. Provider retrieval time is shown below; execution prices may differ.",
    supported: "Supported coins",
    language: "Language",
    recent: "Latest purchases",
    viewAll: "View all",
    records: "records",
    backupReady: "Backup downloaded.",
    concentration: "Largest holding",
    noPositions: "No positions yet",
    historyTable: "View snapshot values",
    snapshotDate: "Date",
    staleShort: "Cached",
    liveShort: "Fresh",
    dataTimeHelp:
      "Retrieval time is when Folio received the quote, not a provider trade timestamp.",
    start: "Start with your first purchase",
    totalQuantity: "Coins held",
    estimated: "Indicative valuation",
    portfolioLabel: "Personal portfolio",
    allTime: "Since first visit",
    about: "About Folio",
    aboutHelp:
      "An independent crypto portfolio tracker. Built for recording holdings and understanding their value.",
    deleteHistory:
      "Deleting or editing a purchase does not rewrite previous daily snapshots.",
    future: "Dates must be today or earlier.",
    backupCount: "Purchases in backup",
  },
  ru: {
    assets: "Мои активы",
    assetsHelp:
      "Все позиции, их стоимость покупки и текущая оценка. Изменить отдельную запись можно в истории покупок.",
    appearance: "Оформление",
    appearanceHelp:
      "Девять тем для вашего портфеля. Выбор сохраняется на этом устройстве.",
    quoteHint: "Текущая котировка · USD",
    manualQuote:
      "Свежей котировки нет. Введите фактическую цену покупки вручную.",
    historicalPrice:
      "Это текущая ориентировочная котировка, а не цена покупки в прошлом. Смена даты не изменит введённую цену.",
    useQuote: "Подставить текущую котировку",
    overview: "Обзор",
    purchases: "История покупок",
    markets: "Рынок",
    settings: "Ваши данные",
    portfolio: "Мой портфель",
    subtitle: "Всё, чем вы владеете, — в одном месте.",
    add: "Добавить покупку",
    edit: "Изменить покупку",
    save: "Сохранить покупку",
    cancel: "Отмена",
    remove: "Удалить",
    confirmDelete:
      "Удалить эту покупку? Количество монет и вложенная сумма изменятся.",
    saved: "Покупка сохранена на этом устройстве.",
    deleted: "Покупка удалена.",
    undo: "Отменить",
    value: "Стоимость портфеля",
    cost: "Всего вложено",
    pnl: "Нереализованный P&L",
    roi: "Доходность вложений",
    feesIncluded: "С учётом комиссий",
    unrealized: "Текущая стоимость минус вложения",
    noCost: "Нет стоимости покупки",
    holdings: "Ваши позиции",
    coin: "Монета",
    quantity: "Количество",
    average: "Средняя цена покупки",
    price: "Текущая цена",
    purchasePrice: "Цена за монету · USD",
    total: "Стоимость",
    allocation: "Состав портфеля",
    history: "История портфеля",
    observed: "Стоимость",
    costLine: "Вложено",
    historyHelp:
      "Ежедневные оценки при использовании Folio. Покупки и правки тоже меняют стоимость; это не график доходности.",
    historyEmpty: "Здесь начнётся ваша история",
    historyEmptyHelp:
      "После первой покупки Folio сохраняет оценку за день, когда вы заходите со свежими ценами. Вернитесь в другой день, чтобы увидеть динамику.",
    empty: "Начните свой портфель.",
    emptyHelp:
      "Запишите первую покупку криптовалюты, чтобы увидеть её стоимость и доходность. Подключать кошелёк не нужно.",
    local: "На этом устройстве",
    localHelp:
      "Портфель хранится в этом браузере. Экспортируйте копию, чтобы сохранить данные или перенести их на другое устройство.",
    refresh: "Обновить цены",
    refreshing: "Обновляем цены…",
    fetched: "Получено",
    source: "Источник",
    stale: "Цены из кэша: обновление не удалось или прошло более 5 минут.",
    offline:
      "Цены недоступны. Проверьте соединение и обновите. Покупки сохранены.",
    unknown: "Ожидаем цены",
    fee: "Комиссия · USD",
    date: "Дата покупки",
    note: "Заметка (необязательно)",
    notePlaceholder: "Например, ежемесячная покупка",
    purchaseTotal: "Стоимость покупки",
    invalidPurchase:
      "Проверьте монету, положительное количество, неотрицательные цену и комиссию и корректную дату не позднее сегодняшней.",
    close: "Закрыть",
    search: "Найти монету",
    noResults: "Монеты не найдены.",
    ledgerHelp:
      "История ваших покупок. Исправьте запись, чтобы изменить количество, дату или стоимость.",
    actions: "Действия",
    backup: "Сохраните копию портфеля",
    export: "Экспорт копии",
    import: "Импорт копии",
    importHelp:
      "Выберите JSON-копию Folio. Перед заменой данных появится подтверждение.",
    exportCsv: "Экспорт покупок · CSV",
    importReview: "Заменить текущий портфель?",
    importConfirm: "Заменить данными из копии",
    importWarning:
      "Все покупки и история на этом устройстве будут заменены. Сначала экспортируйте текущий портфель, если хотите его сохранить.",
    imported: "Резервная копия загружена.",
    invalidBackup:
      "Это не корректная резервная копия Folio. Текущие данные не изменены.",
    storageError:
      "Хранилище браузера недоступно или заполнено. Изменения не сохраняются. Экспортируйте данные перед закрытием страницы.",
    corrupt:
      "Не удалось прочитать сохранённые данные. Скачайте их для восстановления или импортируйте корректную копию. Ничего не перезаписано.",
    recovery: "Скачать файл восстановления",
    privacy: "Личные данные остаются у вас",
    privacyHelp:
      "Без регистрации, отслеживания и ключей кошелька. Публичные цены запрашиваются у Coinbase, при сбое — у Kraken. Ваши позиции не отправляются этим сервисам.",
    method: "Как считаются показатели",
    methodHelp:
      "Вложения = количество × цена покупки + комиссия. P&L = текущая стоимость − вложения. ROI = P&L ÷ вложения. Покупки одной монеты объединяются со средневзвешенной ценой. Все суммы в USD. Продажи, налоговые отчёты и биржевые сделки не поддерживаются.",
    marketHelp:
      "Ориентировочные цены в USD. Время получения указано внизу; цена реальной сделки может отличаться.",
    supported: "Доступные монеты",
    language: "Язык",
    recent: "Последние покупки",
    viewAll: "Все покупки",
    records: "записей",
    backupReady: "Копия скачана.",
    concentration: "Крупнейшая позиция",
    noPositions: "Пока нет позиций",
    historyTable: "Посмотреть значения",
    snapshotDate: "Дата",
    staleShort: "Из кэша",
    liveShort: "Свежие",
    dataTimeHelp:
      "Время получения — момент загрузки цены в Folio, а не время биржевой сделки.",
    start: "Добавьте первую покупку",
    totalQuantity: "Монет в портфеле",
    estimated: "Ориентировочная оценка",
    portfolioLabel: "Личный портфель",
    allTime: "С первого посещения",
    about: "О Folio",
    aboutHelp:
      "Самостоятельный трекер криптопортфеля для учёта монет и понимания их стоимости.",
    deleteHistory:
      "Удаление и изменение покупок не переписывает оценки прошлых дней.",
    future: "Дата не может быть в будущем.",
    backupCount: "Покупок в копии",
  },
};
export type Language = keyof typeof strings;
export type Text = typeof strings.en;
